// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpZhReBL0Ci9C2dA8hDcLpzCUSPpT2uM',
    appId: '1:784725778735:web:8415567262bbca484f81da',
    messagingSenderId: '784725778735',
    projectId: 'login-soda',
    authDomain: 'login-soda.firebaseapp.com',
    storageBucket: 'login-soda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYC3FdWJcCzPxUrQLRrynUHlDWp1YUvsQ',
    appId: '1:784725778735:android:a7c11e0a0c39ee7d4f81da',
    messagingSenderId: '784725778735',
    projectId: 'login-soda',
    storageBucket: 'login-soda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCviIoGE_0q9r-SFuYpiX2RYht9cxfVn_g',
    appId: '1:784725778735:ios:3208d4823f89d6574f81da',
    messagingSenderId: '784725778735',
    projectId: 'login-soda',
    storageBucket: 'login-soda.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCviIoGE_0q9r-SFuYpiX2RYht9cxfVn_g',
    appId: '1:784725778735:ios:c1b3e6189e63b8094f81da',
    messagingSenderId: '784725778735',
    projectId: 'login-soda',
    storageBucket: 'login-soda.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
